Repository sensu-plugins/sensu-plugins-rabbitmq, pull requests merged in 2018-03, with the labels that each got.

#79 Add documentation on minimum rabbitmq permissions
  README.md
Labels: Type: Documentation

#80 [CVE-2017-8418] - updating rubocop dependency.
  .rubocop.yml
  .travis.yml
  CHANGELOG.md
  Gemfile
  Rakefile
  bin/check-rabbitmq-alive.rb
  bin/check-rabbitmq-amqp-alive.rb
  bin/check-rabbitmq-cluster-health.rb
  bin/check-rabbitmq-consumers.rb
  bin/check-rabbitmq-messages.rb
  bin/check-rabbitmq-network-partitions.rb
  bin/check-rabbitmq-node-health.rb
  bin/check-rabbitmq-node-usage.rb
  bin/check-rabbitmq-queue-drain-time.rb
  bin/check-rabbitmq-queue.rb
  bin/check-rabbitmq-queues-synchronised.rb
  bin/check-rabbitmq-stomp-alive.rb
  bin/metrics-rabbitmq-exchange.rb
  bin/metrics-rabbitmq-overview.rb
  bin/metrics-rabbitmq-queue.rb
  lib/sensu-plugins-rabbitmq.rb
  lib/sensu-plugins-rabbitmq/check.rb
  lib/sensu-plugins-rabbitmq/metrics.rb
  lib/sensu-plugins-rabbitmq/rabbitmq.rb
  sensu-plugins-rabbitmq.gemspec
  test/check-rabbitmq-queue_spec.rb
  test/check-rabbitmq-queues-synchronised_spec.rb
  test/metrics-rabbitmq-exchange_spec.rb
  test/metrics-rabbitmq-queue_spec.rb
  test/spec_helper.rb
Labels: Impact: Breaking Change, Type: Security

#81 [CVE-2017-17042] update vulnerable `yard` dependency
  CHANGELOG.md
  sensu-plugins-rabbitmq.gemspec
Labels: Status: Needs Review, Type: Security

#82 Add option to skip cert verification
  CHANGELOG.md
  bin/check-rabbitmq-queues-synchronised.rb
  test/check-rabbitmq-queues-synchronised_spec.rb
Labels: Status: Needs Review, Type: Enhancement
